codecov:
  require_ci_to_pass: True
  notify:
    wait_for_ci: True



coverage:
  precision: 2
  round: down
  range: 80...90

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project:
      default:
        enabled: True
        target: 1
        threshold: 0.1
    patch:
      default:
        enabled: on

ignore:
  - "**/*.ipynb"
  - docs
  - docker
  - binder
  - .github
  - .git

fixes:
  - "/home/runner/work/whoosh-reloaded/whoosh-reloaded/::https://github.com/Sygil-Dev/whoosh-reloaded/"  # attemtp to fix the paths for the github actions.
